/**
 * Created by MAc on 2017/12/30.
 */
const navigation = {
    name:'navigation',
    navItems:{
        'home':{
            link:'/parent/home',
            title:'首页'
        },
        'productInformation':{
            link:'/parent/product-information',
            title:'产品信息',
            width:'600px',
            show:true,
            children:[
                {
                    link:'',
                    name:'hp',
                    title:'HP产品',
                    children:[
                        {
                            link:'product-list',
                            title:'商用台式机',
                            id:1
                        },{
                            link:'product-list',
                            title:'服务器',
                            id:2
                        },{
                            link:'product-list',
                            title:'存储',
                            id:3
                        }
                    ]
                },{
                    link:'',
                    name:'ibm',
                    title:'IBM产品',
                    children:[
                        {
                            link:'',
                            title:'IBM服务器',
                        },{
                            link:'',
                            title:'存储',
                        }
                    ]
                },{
                    link:'',
                    name:'lenovo',
                    title:'lenovo产品',
                    children:[
                        {
                            link:'',
                            title:'台式机'
                        },{
                            link:'',
                            title:'服务器'
                        }
                    ]
                },{
                    link:'',
                    name:'dell',
                    title:'DELL产品',
                    children:[
                        {
                            link:'',
                            title:'台式机'
                        },{
                            link:'',
                            title:'服务器'
                        }
                    ]
                },{
                    link:'',
                    name:'langchao',
                    title:'浪潮产品',
                    children:[
                        {
                            link:'',
                            title:'服务器'
                        },{
                            link:'',
                            title:'存储'
                        }
                    ]
                },{
                    link:'',
                    name:'cisco',
                    title:'Cisco产品',
                    children:[
                        {
                            link:'',
                            title:' 网络产品'
                        }
                    ]
                },{
                    link:'',
                    name:'h3c',
                    title:'H3C产品',
                    children:[
                        {
                            link:'',
                            title:' 网络产品'
                        }
                    ]
                }
            ]
        },
        'pressCenter':{
            link:'/parent/press-center',
            title:'新闻中心',

        },
        'successfulCase':{
            link:'/parent/successful-case',
            title:'成功案例'
        },
        'solution':{
            link:'/parent/solution',
            title:'解决方案'
        },
        'technicalSupport':{
            link:'/parent/technical-support',
            title:'技术支持'
        },
        'about':{
            link:'/parent/about',
            title:'关于公司'
        },
        'joinUs':{
            link:'/parent/join-us',
            title:'加入我们'
        },
        'contactUs':{
            link:'/parent/contact-us',
            title:'联系我们'
        }
    }

};
module.exports = navigation;
