let navItems = [
    {
        id:1,
        title:'首页',
        link:'/parent/home',
        children:null,
        show:false
    },{
        id:2,
        title:'产品信息',
        link:'/parent/product-information',
        children:[],
        show:false
    },{
        id:3,
        link:'/parent/press-center',
        title:'新闻中心',
        children:null,
        show:false
    },{
        id:4,
        link:'/parent/successful-case',
        title:'成功案例',
        children:null,
        show:false
    },{
        id:5,
        link:'/parent/solution',
        title:'解决方案',
        children:null,
        show:false
    },{
        id:6,
        link:'/parent/technical-support',
        title:'技术支持',
        children:null
    },{
        id:7,
        link:'/parent/about',
        title:'关于公司',
        children:null,
        show:false
    },{
        id:8,
        link:'/parent/join-us',
        title:'加入我们',
        children:null,
        show:false
    },{
        id:9
        ,
        link:'/parent/contact-us',
        title:'联系我们',
        children:null,
        show:false
    }
]
export default  navItems;
