let navItems = [
    {
        id:1,
        title:'首页',
        link:'/parent/home',
        children:null,
        show:false
    },{
        id:2,
        title:'产品信息',
        link:'/parent/product-information',
        children:null,
        show:false
    },{
        id:3,
        link:'/parent/press-center',
        name:'press-list',
        title:'新闻中心',
        children:null,
        show:false
    },{
        id:4,
        link:'/parent/successful-case',
        title:'成功案例',
        children:null,
        show:false
    },{
        id:6,
        link:'/parent/solution',
        name:'solution-list',
        title:'解决方案',
        children:null,
        width:'400px',
        show:false
    },{
        id:7,
        link:'/parent/technical-support',
        title:'技术支持',
        children:null
    },{
        id:8,
        link:'/parent/about',
        title:'关于我们',
        children:null,
        show:false
    }
]
export default  navItems;
